template_version: 0.1

network:
  bind:
    port: 443
    ipv4: 185.250.36.148
  file: network.yml

config:
  dir: hubber/config/
plugin:
  file: plugin.yml
auth:
  file: authentication.yml
logs:
  file: log.yml






  
